<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_bot">
  <!-- Parámetros globales -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width"  value="0.02"/>
  <xacro:property name="base_length"  value="0.30"/>
  <xacro:property name="base_width"   value="0.30"/>
  <xacro:property name="base_height"  value="0.08"/>

  <!-- Material simple -->
  <material name="chassis_color"><color rgba="0.1 0.1 0.1 1"/></material>
  <material name="wheel_color"><color rgba="0.15 0.15 0.15 1"/></material>

  <!-- Chasis -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="chassis_color"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="4.0"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia
        ixx="0.02" ixy="0.0" ixz="0.0"
        iyy="0.03" iyz="0.0"
        izz="0.04"/>
    </inertial>
  </link>

  <!-- Ruedas: izquierda y derecha -->
  <xacro:macro name="wheel" params="side sign">
    <link name="${side}_wheel_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <material name="wheel_color"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
          ixx="0.0005" ixy="0.0" ixz="0.0"
          iyy="0.0005" iyz="0.0"
          izz="0.001"/>
      </inertial>
    </link>

    <joint name="${side}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${side}_wheel_link"/>
      <origin xyz="0 ${sign*base_width/2} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Instanciación -->
  <xacro:wheel side="left"  sign=" 1"/>
  <xacro:wheel side="right" sign="-1"/>

  <!-- Sensor LIDAR (Hokuyo) -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.04"/>
      </geometry>
      <origin xyz="0 0 ${base_height+0.05}" rpy="0 0 0"/>
      <material name="chassis_color"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="laser_link"/>
    <origin xyz="0 0 ${base_height+0.05}" rpy="0 0 0"/>
  </joint>
</robot>
