<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_bot">

  <!-- =========================================================
       PARÁMETROS GENERALES
       ========================================================= -->
  <xacro:property name="wheel_radius"     value="0.05"/>   <!-- 5 cm -->
  <xacro:property name="wheel_width"      value="0.02"/>
  <xacro:property name="base_length"      value="0.25"/>
  <xacro:property name="base_width"       value="0.30"/>
  <xacro:property name="base_height"      value="0.06"/>
  <xacro:property name="wheel_separation" value="${base_width}"/>
  <xacro:property name="wheel_diam"       value="${2*wheel_radius}"/>

  <!-- =========================================================
       MATERIALES
       ========================================================= -->
  <material name="chassis_color"><color rgba="0.3 0.5 0.8 1"/></material> 
  <material name="lidar_color"><color rgba="1.0 0.5 0.5 1"/></material> 
  <material name="wheel_color"><color rgba="0.6 0.6 0.6 1"/></material>



  <!-- =========================================================
       CHASIS
       ========================================================= -->
  <link name="base_link">
    <!-- Visual for the main body -->
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" rpy="0 0 0"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + base_height/2}"/>
      <material name="chassis_color"/>
    </visual>

    <!-- Visual for the LiDAR support bracket (COSMETIC ONLY) -->
    <visual name="lidar_support_visual">
      <geometry>
        <box size="0.035 0.05 0.09"/>
      </geometry>
      <origin xyz="${base_length/2} 0 ${base_height + 0.02}" rpy="0 0 0"/>
      <material name="chassis_color"/>
    </visual>

    <!-- Collision for the main body (Unchanged) -->
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + base_height/2}"/>
    </collision>
    
    <!-- Inertial properties (Unchanged) -->
    <inertial>
      <mass value="4.0"/>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.03" iyz="0.0" izz="0.04"/>
    </inertial>
  </link>

  <!-- =========================================================
       MACRO RUEDA
       ========================================================= -->
  <xacro:macro name="wheel" params="name x_offset y_offset">
  <link name="${name}_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="wheel_color"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0"
               iyy="0.0005" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="${name}_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="${name}_link"/>
    <origin xyz="${x_offset} ${y_offset} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
</xacro:macro>

  <!-- Instanciación de ruedas -->
  <!-- Ruedas delanteras -->
<xacro:wheel name="front_left_wheel"  x_offset="${ base_length/2 - 0.05}" y_offset=" ${ base_width/2}" />
<xacro:wheel name="front_right_wheel" x_offset="${ base_length/2 - 0.05}" y_offset="-${ base_width/2}" />

<!-- Ruedas traseras -->
<xacro:wheel name="rear_left_wheel"   x_offset="-${ base_length/2 - 0.05}" y_offset=" ${ base_width/2}" />
<xacro:wheel name="rear_right_wheel"  x_offset="-${ base_length/2 - 0.05}" y_offset="-${ base_width/2}" />


  <!-- =========================================================
       SENSOR LIDAR
       ========================================================= -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.04"/>
      </geometry>
      <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
      <material name="lidar_color"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="laser_link"/>
    <origin xyz="${base_length/2 + 0.01} 0 ${base_height}" rpy="0 0 0"/>
  </joint>

  <!-- =========================================================
       PLUGINS GAZEBO
       ========================================================= -->
  <!-- Dif-Drive                                               -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>

      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_diam}</wheel_diameter>

      <ros>
        <namespace>/lidar_bot</namespace>
        <remapping>cmd_vel:=/cmd_vel</remapping>
        <remapping>odom:=/odom</remapping>
      </ros>

      <publish_tf>true</publish_tf>
      <publish_odom>true</publish_odom>        
      <publish_odom_tf>true</publish_odom_tf>  
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <update_rate>50</update_rate>
    </plugin>
  </gazebo>


  <!-- LIDAR como sensor ray   -->
  <gazebo reference="laser_link">
    <sensor type="ray" name="lidar">
      <update_rate>20</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.5708</min_angle>
            <max_angle>1.5708</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>6.0</max>
        </range>
      </ray>
      <plugin name="gazebo_laser" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <!-- remapea la salida interna ~/out a /scan -->
          <remapping>~/out:=scan</remapping>
        </ros>
        <!-- publica LaserScan en vez de PointCloud2 -->
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>
